const ActionTypes = {
  COUNTER_PLUS: "COUNTER_PLUS",
  COUNTER_MINUS: "COUNTER_MINUS",

  //   /products
  GET_PRODUCTDATA_LOADING: "GET_PRODUCTDATA_LOADING",
  GET_PRODUCTDATA_SUCCESS: "GET_PRODUCTDATA_SUCCESS",
  GET_PRODUCTDATA_FAIL: "GET_PRODUCTDATA_FAIL",

  //ADD_TO_CART
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_TO_CART: "REMOVE_TO_CART",
};

export default ActionTypes;
